" VPETKOV VIMRC VIM CONFIG FILE "

"""" Movement
" work more logically with wrapped lines
noremap j gj
noremap <down> gj
noremap k gk
noremap <up> gk

"""" Searching and Patterns
set ignorecase							" search is case insensitive
set smartcase							" search case sensitive if caps on 
set incsearch							" show best match so far

"""" Display
set background=light					" I use dark background
set lazyredraw							" Don't repaint when scripts are running
set scrolloff=2							" Keep 3 lines below and above the cursor
set ruler								" line numbers and column the cursor is on
set number								" Show line numbering
set numberwidth=1						" Use 1 col + 1 space for numbers
" colorscheme tango						" Use tango colors

"""" Editing
set backspace=2							" Backspace over anything! (Super backspace!)
set showmatch							" Briefly jump to the previous matching paren
set matchtime=2							" For .2 seconds
set formatoptions-=tc					" I can format for myself, thank you very much
set tabstop=4							" Tab stop of 4
set shiftwidth=4						" sw 4 spaces (used on auto indent)
set softtabstop=4						" 4 spaces as a tab for bs/del
set autoindent							" Keep indent on next line

"""" Mouse
set mouse=ni							" mouse only in normal and input mode.
set mousefocus=on						" Focus mose on current buffer.

" Toggle the tag list bar
nmap <F9> :TlistToggle<CR>

"""" Python
" execute
autocmd FileType python map <buffer> <F5> :w<CR>:!/usr/bin/env python % <CR>
" make tab in spaces
autocmd FileType python set expandtab

" Save all buffers
map <F2> :wa<CR>

" Exit all buffers with q
map q :qa<CR>

" I hate hitting q: or :я instead of :q
nnoremap q: :q
nnoremap :я :q
nnoremap :я! :q!
nnoremap :вя :wq

" Toggle the task list
map <F3> :TaskList<CR>

" we don't want to edit these type of files
set wildignore=*.o,*.obj,*.bak,*.exe,*.pyc,*.swp

" tab navigation (next tab) with alt left / alt right
nnoremap  <a-right>  gt
nnoremap  <a-left>   gT

" Ctrl + Arrows - Move around quickly
nnoremap  <c-up>     {
nnoremap  <c-down>   }
nnoremap  <c-right>  El
nnoremap  <c-down>   Bh

" Shift + Arrows - Visually Select text
nnoremap  <s-up>     Vk
nnoremap  <s-down>   Vj
nnoremap  <s-right>  vl
nnoremap  <s-left>   vh

if &diff
" easily handle diffing 
   vnoremap < :diffget<CR>
   vnoremap > :diffput<CR>
else
" visual shifting (builtin-repeat)
   vnoremap < <gv                       
   vnoremap > >gv 
endif

"set hlsearch
"nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" <C-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>

"""" Syntax
syntax on
filetype plugin on

autocmd FileType python set omnifunc=pythoncomplete#Complete
"autocmd FileType python set complete+=k~/.vim/syntax/python.vim isk+=.,(

"""" miniBuf
let g:miniBufExplMapWindowNavVim = 1 
let g:miniBufExplMapWindowNavArrows = 1 
let g:miniBufExplMapCTabSwitchBufs = 1 
let g:miniBufExplModSelTarget = 1

"""" Statusline
set laststatus=2 "show
"Statusline - filename hour:minutes:seconds Day Date Month Year ==== line,row, percent
set statusline=%F%m%r%h%w\ \%{strftime(\"\%H\:\%M\:\%S\ \%a\ \%d\ \%b\ \%Y\",getftime(expand(\"\%\%\")))}\ %=%=%l,%c\ (%p%%)

"""" spellcheck
:map <F7> :setlocal spell! spelllang=en_us,bg<CR>
:imap <F7> <ESC>:setlocal spell! spelllang=en_us,bg<CR>

"""" български буквички
map зг zg
map ч `
map я q
map в w
map е e
map р r
map т t
map ъ y
map у u
map и i
map о o
map п p
map ш [
map щ ]

map а a
map с s
map д d
map ф f
map г g
map х h
map й j
map к k
map л l

map з z
map ь x
map ц c
map ж v
map б b
map н n
map м m


map Ч ~
map Я Q
map В W
map Е E
map Р R
map Т T
map Ъ Y
map У U
map И I
map О O
map П P
map Ш {
map Щ }

map А A
map С S
map Д D
map Ф F
map Г G
map Х H
map Й J
map К K
map Л L

map З Z
map Ь X
map Ц C
map Ж V
map Б B
map Н N
map М M
